test_that("gams_problem validates objective and equations", {
  model <- gams_model("transport")
  i <- gams_set(model, "i", records = c("seattle", "san-diego"))
  j <- gams_set(model, "j", records = c("new-york", "chicago"))
  x <- gams_variable(model, "x", domain = c(i, j), type = "positive")
  supply <- gams_equation(model, "supply", domain = i)

  supply[i] <- gams_sum(j, x[i, j]) <= 1

  expect_error(
    gams_problem(model, equations = supply, objective = x[i, j]),
    class = "gamsr_error_invalid_objective"
  )
  expect_error(
    gams_problem(model, equations = c(supply, supply), objective = gams_sum(c(i, j), x[i, j])),
    class = "gamsr_error_duplicate_name"
  )
})

test_that("LP problems reject discrete variables", {
  model <- gams_model("discrete_model")
  x <- gams_variable(model, "x", type = "binary")
  e <- gams_equation(model, "e")
  e[] <- x <= 1

  expect_error(
    gams_problem(model, equations = e, objective = x, problem = "LP"),
    class = "gamsr_error_invalid_problem"
  )
  expect_s3_class(
    gams_problem(model, equations = e, objective = x, problem = "MIP"),
    "gams_problem"
  )
})

test_that("model_ir exposes normalized compiler data", {
  model <- gams_model("scalar_lp")
  x <- gams_variable(model, "x", type = "free")
  e <- gams_equation(model, "balance")
  e[] <- x >= 1

  problem <- gams_problem(model, equations = e, objective = x, sense = "min", problem = "LP")
  ir <- model_ir(problem)

  expect_s3_class(ir, "gams_ir")
  expect_identical(ir$problem_name, "scalar_lp_problem")
  expect_identical(ir$objective_variable, "GAMSr_obj_scalar_lp_problem")
  expect_identical(ir$objective_equation, "GAMSr_obj_def_scalar_lp_problem_def")
})

test_that("generated_gams renders a scalar LP deterministically", {
  model <- gams_model("scalar_lp")
  x <- gams_variable(model, "x", type = "free")
  e <- gams_equation(model, "balance")
  e[] <- x >= 1

  problem <- gams_problem(
    model,
    name = "scalar_lp_problem",
    equations = e,
    objective = x,
    sense = "min",
    problem = "LP"
  )

  expect_identical(
    generated_gams(problem),
    paste(
      "$onText",
      "Generated by GAMSr for problem `scalar_lp_problem`.",
      "This file is deterministic compile-only output.",
      "$offText",
      "",
      "Variables GAMSr_obj_scalar_lp_problem;",
      "Variables x;",
      "",
      "Equations balance, GAMSr_obj_def_scalar_lp_problem_def;",
      "",
      "balance.. x =g= 1;",
      "GAMSr_obj_def_scalar_lp_problem_def.. GAMSr_obj_scalar_lp_problem =e= x;",
      "",
      "Model scalar_lp_problem / balance, GAMSr_obj_def_scalar_lp_problem_def /;",
      "Solve scalar_lp_problem using LP minimizing GAMSr_obj_scalar_lp_problem;",
      sep = "\n"
    )
  )
})

test_that("generated_gams renders the transportation model deterministically", {
  model <- gams_model("transport")
  i <- gams_set(
    model,
    "i",
    records = c("seattle", "san-diego"),
    description = "canning plants"
  )
  j <- gams_set(
    model,
    "j",
    records = c("new-york", "chicago", "topeka"),
    description = "markets"
  )
  a <- gams_parameter(
    model,
    "a",
    domain = i,
    records = c(seattle = 350, `san-diego` = 600)
  )
  b <- gams_parameter(
    model,
    "b",
    domain = j,
    records = c(`new-york` = 325, chicago = 300, topeka = 275)
  )
  c <- gams_parameter(
    model,
    "c",
    domain = c(i, j),
    records = data.frame(
      i = c("seattle", "seattle", "seattle", "san-diego", "san-diego", "san-diego"),
      j = c("new-york", "chicago", "topeka", "new-york", "chicago", "topeka"),
      value = c(0.225, 0.153, 0.162, 0.225, 0.162, 0.126)
    )
  )
  x <- gams_variable(model, "x", domain = c(i, j), type = "positive")
  supply <- gams_equation(model, "supply", domain = i)
  demand <- gams_equation(model, "demand", domain = j)

  supply[i] <- gams_sum(j, x[i, j]) <= a[i]
  demand[j] <- gams_sum(i, x[i, j]) >= b[j]

  problem <- gams_problem(
    model,
    name = "transport_problem",
    equations = c(supply, demand),
    objective = gams_sum(c(i, j), c[i, j] * x[i, j]),
    sense = "min",
    problem = "LP"
  )

  expect_identical(
    generated_gams(problem),
    paste(
      "$onText",
      "Generated by GAMSr for problem `transport_problem`.",
      "This file is deterministic compile-only output.",
      "$offText",
      "",
      "Set i \"canning plants\" / seattle, san-diego /;",
      "Set j \"markets\" / new-york, chicago, topeka /;",
      "",
      "Parameter a(i) /",
      "    seattle 350",
      "    san-diego 600",
      "/;",
      "Parameter b(j) /",
      "    new-york 325",
      "    chicago 300",
      "    topeka 275",
      "/;",
      "Parameter c(i,j) /",
      "    seattle.new-york 0.225",
      "    seattle.chicago 0.153",
      "    seattle.topeka 0.162",
      "    san-diego.new-york 0.225",
      "    san-diego.chicago 0.162",
      "    san-diego.topeka 0.126",
      "/;",
      "",
      "Variables GAMSr_obj_transport_problem;",
      "Positive Variables x(i,j);",
      "",
      "Equations supply(i), demand(j), GAMSr_obj_def_transport_problem_def;",
      "",
      "supply(i).. sum(j, x(i,j)) =l= a(i);",
      "demand(j).. sum(i, x(i,j)) =g= b(j);",
      paste0(
        "GAMSr_obj_def_transport_problem_def.. GAMSr_obj_transport_problem =e= ",
        "sum((i,j), c(i,j) * x(i,j));"
      ),
      "",
      "Model transport_problem / supply, demand, GAMSr_obj_def_transport_problem_def /;",
      "Solve transport_problem using LP minimizing GAMSr_obj_transport_problem;",
      sep = "\n"
    )
  )
})
