$onText
Generated by GAMSr for problem `scalar_lp_problem`.
This file is deterministic compile-only output.
$offText

Variables GAMSr_obj_scalar_lp_problem;
Variables x;

Equations balance, GAMSr_obj_def_scalar_lp_problem_def;

balance.. x =g= 1;
GAMSr_obj_def_scalar_lp_problem_def.. GAMSr_obj_scalar_lp_problem =e= x;

Model scalar_lp_problem / balance, GAMSr_obj_def_scalar_lp_problem_def /;
Solve scalar_lp_problem using LP minimizing GAMSr_obj_scalar_lp_problem;
