$onText
Generated by GAMSr for problem `transport_problem`.
This file is deterministic compile-only output.
$offText

Set i "canning plants" / seattle, san-diego /;
Set j "markets" / new-york, chicago, topeka /;

Parameter a(i) /
    seattle 350
    san-diego 600
/;
Parameter b(j) /
    new-york 325
    chicago 300
    topeka 275
/;
Parameter c(i,j) /
    seattle.new-york 0.225
    seattle.chicago 0.153
    seattle.topeka 0.162
    san-diego.new-york 0.225
    san-diego.chicago 0.162
    san-diego.topeka 0.126
/;

Variables GAMSr_obj_transport_problem;
Positive Variables x(i,j);

Equations supply(i), demand(j), GAMSr_obj_def_transport_problem_def;

supply(i).. sum(j, x(i,j)) =l= a(i);
demand(j).. sum(i, x(i,j)) =g= b(j);
GAMSr_obj_def_transport_problem_def.. GAMSr_obj_transport_problem =e= sum((i,j), c(i,j) * x(i,j));

Model transport_problem / supply, demand, GAMSr_obj_def_transport_problem_def /;
Solve transport_problem using LP minimizing GAMSr_obj_transport_problem;
