#' Build a normalized model IR
#'
#' @param problem A problem created by [gams_problem()].
#'
#' @return A list with class `gams_ir`.
#' @export
model_ir <- function(problem) {
  if (!inherits(problem, "gams_problem")) {
    gamsr_abort(
      "`problem` must be created by `gams_problem()`.",
      class = "gamsr_error_invalid_problem"
    )
  }

  symbols <- problem$model$symbols()
  objective_variable <- choose_private_name(problem$model, c("GAMSr_obj", problem$name))
  objective_equation <- choose_private_name(
    problem$model,
    c("GAMSr_obj_def", problem$name, "def")
  )

  structure(
    list(
      package = "GAMSr",
      model_name = problem$model$name,
      problem_name = problem$name,
      problem_type = problem$problem,
      sense = problem$sense,
      symbols = symbols,
      sets = Filter(function(symbol) inherits(symbol, "gams_set"), symbols),
      aliases = Filter(function(symbol) inherits(symbol, "gams_alias"), symbols),
      parameters = Filter(function(symbol) inherits(symbol, "gams_parameter"), symbols),
      variables = Filter(function(symbol) inherits(symbol, "gams_variable"), symbols),
      equations = problem$equations,
      objective = problem$objective,
      objective_variable = objective_variable,
      objective_equation = objective_equation
    ),
    class = "gams_ir"
  )
}

#' Generate deterministic GAMS source
#'
#' @param problem A problem created by [gams_problem()].
#'
#' @return A single character string containing GAMS source code.
#' @export
generated_gams <- function(problem) {
  render_gams_ir(model_ir(problem))
}

choose_private_name <- function(model, parts) {
  base <- sanitize_private_name(paste(parts, collapse = "_"))
  existing <- tolower(vapply(model$symbols(), `[[`, "name", FUN.VALUE = character(1L)))
  candidate <- base
  i <- 1L

  while (tolower(candidate) %in% existing || tolower(candidate) %in% .gams_reserved_words) {
    i <- i + 1L
    candidate <- paste0(base, "_", i)
  }

  validate_symbol_name(candidate)
}

sanitize_private_name <- function(name) {
  name <- gsub("[^A-Za-z0-9_]", "_", name, perl = TRUE)
  name <- gsub("_+", "_", name, perl = TRUE)
  name <- sub("^_+", "", name, perl = TRUE)
  if (!grepl("^[A-Za-z]", name)) {
    name <- paste0("GAMSr_", name)
  }
  substr(name, 1L, 63L)
}

render_gams_ir <- function(ir, data_source = c("inline", "gdx"), input_file = NULL) {
  data_source <- match.arg(data_source)
  sections <- list(
    render_header(ir),
    render_sets(ir$sets, include_records = identical(data_source, "inline")),
    render_aliases(ir$aliases),
    render_parameters(ir$parameters, include_records = identical(data_source, "inline")),
    render_gdx_load(ir, input_file, enabled = identical(data_source, "gdx")),
    render_variables(ir$variables, ir$objective_variable),
    render_equation_declarations(ir$equations, ir$objective_equation),
    render_equation_definitions(ir),
    render_model_and_solve(ir)
  )

  section_text <- vapply(
    Filter(function(section) length(section) > 0L, sections),
    paste,
    character(1L),
    collapse = "\n"
  )
  paste(section_text, collapse = "\n\n")
}

render_aliases <- function(aliases) {
  if (length(aliases) == 0L) {
    return(character())
  }

  vapply(
    aliases,
    function(alias) sprintf("Alias (%s, %s);", alias$base_set$name, alias$name),
    character(1L),
    USE.NAMES = FALSE
  )
}

render_header <- function(ir) {
  c(
    "$onText",
    sprintf("Generated by GAMSr for problem `%s`.", ir$problem_name),
    "This file is deterministic compile-only output.",
    "$offText"
  )
}

render_sets <- function(sets, include_records = TRUE) {
  if (length(sets) == 0L) {
    return(character())
  }

  unlist(lapply(sets, render_set, include_records = include_records), use.names = FALSE)
}

render_set <- function(set, include_records = TRUE) {
  description <- render_description(set$description)
  if (!isTRUE(include_records)) {
    return(sprintf("Set %s%s;", set$name, description))
  }

  if (nrow(set$records) == 0L) {
    return(sprintf("Set %s%s / /;", set$name, description))
  }

  records <- paste(format_gams_label(set$records$label), collapse = ", ")
  sprintf("Set %s%s / %s /;", set$name, description, records)
}

render_parameters <- function(parameters, include_records = TRUE) {
  if (length(parameters) == 0L) {
    return(character())
  }

  unlist(lapply(parameters, render_parameter, include_records = include_records), use.names = FALSE)
}

render_parameter <- function(parameter, include_records = TRUE) {
  domain <- render_domain(parameter$domain)
  description <- render_description(parameter$description)

  if (length(parameter$domain) == 0L) {
    if (!isTRUE(include_records)) {
      return(sprintf("Scalar %s%s;", parameter$name, description))
    }
    value <- if (nrow(parameter$records) == 0L) 0 else parameter$records$value[[1L]]
    return(sprintf(
      "Scalar %s%s / %s /;",
      parameter$name,
      description,
      format_constant(value)
    ))
  }

  if (nrow(parameter$records) == 0L) {
    return(sprintf("Parameter %s%s%s;", parameter$name, domain, description))
  }
  if (!isTRUE(include_records)) {
    return(sprintf("Parameter %s%s%s;", parameter$name, domain, description))
  }

  c(
    sprintf("Parameter %s%s%s /", parameter$name, domain, description),
    paste0("    ", render_parameter_records(parameter)),
    "/;"
  )
}

render_parameter_records <- function(parameter) {
  key_columns <- domain_names(parameter$domain)
  apply(parameter$records, 1L, function(row) {
    key <- paste(format_gams_label(unname(row[key_columns])), collapse = ".")
    paste(key, format_constant(as.numeric(row[["value"]])))
  })
}

render_gdx_load <- function(ir, input_file, enabled = FALSE) {
  if (!isTRUE(enabled)) {
    return(character())
  }

  load_symbols <- c(
    vapply(ir$sets, `[[`, "name", FUN.VALUE = character(1L)),
    vapply(ir$parameters, `[[`, "name", FUN.VALUE = character(1L))
  )
  if (length(load_symbols) == 0L) {
    return(character())
  }
  if (is.null(input_file)) {
    gamsr_abort(
      "`input_file` is required when rendering GDX-backed source.",
      class = "gamsr_error_invalid_path"
    )
  }

  c(
    sprintf("$gdxIn %s", quote_gams_text(input_file)),
    sprintf("$load %s", paste(load_symbols, collapse = " ")),
    "$gdxIn"
  )
}

render_variables <- function(variables, objective_variable) {
  sections <- list(sprintf("Variables %s;", objective_variable))
  sections <- c(sections, render_variable_group("free", "Variables", variables))
  sections <- c(sections, render_variable_group("positive", "Positive Variables", variables))
  sections <- c(sections, render_variable_group("negative", "Negative Variables", variables))
  sections <- c(sections, render_variable_group("binary", "Binary Variables", variables))
  sections <- c(sections, render_variable_group("integer", "Integer Variables", variables))
  unlist(Filter(length, sections), use.names = FALSE)
}

render_variable_group <- function(type, keyword, variables) {
  variables <- Filter(function(variable) identical(variable$type, type), variables)
  if (length(variables) == 0L) {
    return(character())
  }
  declarations <- vapply(variables, render_symbol_with_domain, character(1L))
  sprintf("%s %s;", keyword, paste(declarations, collapse = ", "))
}

render_equation_declarations <- function(equations, objective_equation) {
  names <- c(vapply(equations, render_symbol_with_domain, character(1L)), objective_equation)
  sprintf("Equations %s;", paste(names, collapse = ", "))
}

render_equation_definitions <- function(ir) {
  definitions <- vapply(ir$equations, render_equation_definition, character(1L))
  objective <- sprintf(
    "%s.. %s =e= %s;",
    ir$objective_equation,
    ir$objective_variable,
    format_gams_expression(ir$objective)
  )
  c(definitions, objective)
}

render_equation_definition <- function(equation) {
  lhs <- render_symbol_with_domain(equation)
  sprintf("%s.. %s;", lhs, format_gams_expression(equation$definition$expression))
}

render_model_and_solve <- function(ir) {
  equations <- c(
    vapply(ir$equations, `[[`, "name", FUN.VALUE = character(1L)),
    ir$objective_equation
  )
  direction <- if (identical(ir$sense, "min")) "minimizing" else "maximizing"
  c(
    sprintf("Model %s / %s /;", ir$problem_name, paste(equations, collapse = ", ")),
    sprintf(
      "Solve %s using %s %s %s;",
      ir$problem_name,
      ir$problem_type,
      direction,
      ir$objective_variable
    )
  )
}

render_symbol_with_domain <- function(symbol) {
  paste0(symbol$name, render_domain(symbol$domain))
}

render_domain <- function(domain) {
  if (length(domain) == 0L) {
    return("")
  }
  paste0("(", paste(domain_names(domain), collapse = ","), ")")
}

render_description <- function(description) {
  if (is.null(description)) {
    return("")
  }
  paste0(" ", quote_gams_text(description))
}

quote_gams_text <- function(text) {
  paste0('"', gsub('"', '""', text, fixed = TRUE), '"')
}
